name: License question
about: Have a question about our open source license?
title: "[License] "
labels: ["license", "question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about [the annotation toolkit's open source license](https://github.com/github/annotation-toolkit/blob/main/LICENSE.md)?
  - type: textarea
    id: question
    attributes:
      label: License question
      description: Please ask your question here. The more information we have, the easier it will be to address the question.
    validations:
      required: true
  - type: checkboxes
    id: alt-text
    attributes:
      label: Alt text
      description: Descriptive text alternatives have been provided for any images added to this Issue. How to [add alt text to images in Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images).
      options:
        - label: My images use descriptive alt text.
          required: true
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/github/annotation-toolkit/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true